import type { RankTier, UserProfileRecord } from "../types.js";

const BASE_DATE = "2026-03-11";

function makePuzzleSkills(seed: number) {
  return {
    rotate_pipes: Math.min(99, 30 + seed * 7),
    number_grid: Math.min(99, 28 + seed * 6),
    pattern_match: Math.min(99, 32 + seed * 8),
    word_scramble: Math.min(99, 22 + seed * 7),
    tile_slide: Math.min(99, 26 + seed * 6),
    sudoku_mini: Math.min(99, 24 + seed * 5),
    word_search: Math.min(99, 18 + seed * 5),
    maze: Math.min(99, 20 + seed * 6),
    memory_grid: Math.min(99, 18 + seed * 6),
  };
}

export function getRankTier(elo: number): RankTier {
  if (elo >= 3200) return "master";
  if (elo >= 2600) return "diamond";
  if (elo >= 2000) return "platinum";
  if (elo >= 1400) return "gold";
  if (elo >= 800) return "silver";
  return "bronze";
}

export const BOT_USERS: UserProfileRecord[] = [
  {
    id: "bot-cipher-king",
    username: "CipherKing",
    elo: 2850,
    rank: "diamond",
    level: 54,
    xp: 8200,
    xpToNext: 10000,
    coins: 34000,
    gems: 230,
    wins: 412,
    losses: 123,
    winStreak: 8,
    bestStreak: 21,
    matchesPlayed: 535,
    joinedAt: BASE_DATE,
    isVip: true,
    isBot: true,
    socialLinks: { tiktok: "@cipherking" },
    puzzleSkills: makePuzzleSkills(8),
    nemeses: [],
    friends: [],
  },
  {
    id: "bot-quick-mind",
    username: "QuickMind",
    elo: 1420,
    rank: "gold",
    level: 22,
    xp: 2100,
    xpToNext: 4000,
    coins: 8200,
    gems: 45,
    wins: 98,
    losses: 76,
    winStreak: 3,
    bestStreak: 9,
    matchesPlayed: 174,
    joinedAt: BASE_DATE,
    isVip: false,
    isBot: true,
    socialLinks: {},
    puzzleSkills: makePuzzleSkills(5),
    nemeses: [],
    friends: [],
  },
  {
    id: "bot-grid-witch",
    username: "GridWitch",
    elo: 2100,
    rank: "platinum",
    level: 38,
    xp: 5600,
    xpToNext: 7000,
    coins: 22000,
    gems: 150,
    wins: 267,
    losses: 145,
    winStreak: 2,
    bestStreak: 15,
    matchesPlayed: 412,
    joinedAt: BASE_DATE,
    isVip: true,
    isBot: true,
    socialLinks: { facebook: "gridwitch" },
    puzzleSkills: makePuzzleSkills(7),
    nemeses: [],
    friends: [],
  },
  {
    id: "bot-blaze-logic",
    username: "BlazeLogic",
    elo: 1850,
    rank: "gold",
    level: 31,
    xp: 4200,
    xpToNext: 6000,
    coins: 15600,
    gems: 95,
    wins: 178,
    losses: 110,
    winStreak: 0,
    bestStreak: 11,
    matchesPlayed: 288,
    joinedAt: BASE_DATE,
    isVip: false,
    isBot: true,
    socialLinks: { tiktok: "@blazelogic" },
    puzzleSkills: makePuzzleSkills(6),
    nemeses: [],
    friends: [],
  },
  {
    id: "bot-master-vex",
    username: "MasterVex",
    elo: 3350,
    rank: "master",
    level: 72,
    xp: 12000,
    xpToNext: 15000,
    coins: 58000,
    gems: 420,
    wins: 623,
    losses: 87,
    winStreak: 14,
    bestStreak: 31,
    matchesPlayed: 710,
    joinedAt: BASE_DATE,
    isVip: true,
    isBot: true,
    socialLinks: { tiktok: "@mastervex", facebook: "mastervex" },
    puzzleSkills: makePuzzleSkills(9),
    nemeses: [],
    friends: [],
  },
  {
    id: "bot-puzzle-pawn",
    username: "PuzzlePawn",
    elo: 620,
    rank: "bronze",
    level: 8,
    xp: 800,
    xpToNext: 1500,
    coins: 2400,
    gems: 10,
    wins: 23,
    losses: 34,
    winStreak: 1,
    bestStreak: 4,
    matchesPlayed: 57,
    joinedAt: BASE_DATE,
    isVip: false,
    isBot: true,
    socialLinks: {},
    puzzleSkills: makePuzzleSkills(2),
    nemeses: [],
    friends: [],
  },
];

export function createGuestProfile(username?: string): UserProfileRecord {
  const now = new Date().toISOString();
  return {
    id: `player-${crypto.randomUUID()}`,
    username: username?.trim() || `NeonSolver-${Math.floor(100 + Math.random() * 900)}`,
    elo: 1650,
    rank: "gold",
    level: 27,
    xp: 3400,
    xpToNext: 5000,
    coins: 12450,
    gems: 85,
    wins: 142,
    losses: 89,
    winStreak: 5,
    bestStreak: 12,
    matchesPlayed: 231,
    joinedAt: now,
    isVip: false,
    isBot: false,
    socialLinks: {},
    puzzleSkills: makePuzzleSkills(5),
    nemeses: ["bot-cipher-king", "bot-blaze-logic"],
    friends: ["bot-quick-mind", "bot-grid-witch", "bot-puzzle-pawn"],
  };
}
